### ISSUE TITLE
As much as I love IDT, I'm having a hard time pulling more than 500 images per keyword

### ISSUE THREAD

**Issue by Tylersuard** [deliton/idb#9]
**Is your feature request related to a problem? Please describe.**
I often need 5,000+ images for a good deep learning dataset.  I feel frustrated that I can only pull around 500 images per keyword.  For instance, "abstract painting" and "abstract art painting" only got me 500 results each with the duckduckgo engine.

**Describe the solution you'd like**
Perhaps it would be better to be more flexible on the size, and then allow resizing to whatever size necessary.  For instance, when we specify the image size as 512 or whatever, maybe there could be an "any" parameter that takes in all non-duplicate images and can resize them using the other parameters.  Might add more results 👍 

I love the "deleting duplicates" feature by the way.

**Describe alternatives you've considered**

**Additional context**

**Comment by deliton** [comment]
Hey Tyler. I'm glad to hear that this tool is being useful for someone. One strategy I often use is to include the same keyword in different languages like Abstract art, arte abstracto, arte astratta, Sztuka abstrakcyjna, 抽象芸術, and so on. This worked for me in some cases. But we can also discuss some fresh new ideas to increase those numbers as well. I was thinking of mixing different search engines in the same search, adding more search engines, and some data augmentation techniques to increase the total amount of images. What do you think we can do to solve this issue?

**Comment by Tylersuard** [comment]
Good question, and thank you for the response.  I love the tool so much I told Roboflow.com about it.  They are excited too and they want to write a blog post about it.
I don't think the problem comes from different keywords or augmentation, but from the javascript programming of the search engines.  For instance, when I use idt searching for abstract art using duckduckgo, I receive around 500 results.  However, when I use duckduckgo in my browser and I just scroll down, I get well over 1,000 unique-looking results.  It seems that more results will only load if the user scrolls to the bottom of the interface.  It might be possible to add this trigger to any automation that IDT does?

**Comment by MisaelKelviny** [comment]
Hi, @Tylersuard . I'm so happy to see comments like yours about the tool. I think the @deliton option is clear to be working and trying to increase the results obtained. And about the results on the duckduckgo web page in the browser, the IDT filter the results and this could be getting fewer results than the web page of the engine, We listen carefully and debate the issues and improvements about the IDT, and we'll be working on it very soon.  Thank's

**Comment by deliton** [comment]
Wow man, thanks so much . I'll do some debugging in the duckgo script and I'll patch it soon. I'll let you know when I find out what's going on. If you have some feature suggestions, I would be glad to discuss them too.
